export const EventNamesHumanized: Record<string, string> = {
    inscription: 'Account Created',
    updateInscription: 'Account Updated',
    connexionApp: 'Login',
    motDePasseOublie: 'Password forgotten',
    suppressionCompte: 'Account deleted',    
    coachingPlanifie: 'Coaching Statut Update',
    paiementEffectue: 'Payment Accepted',
    telechargementBusinessPlanDownload: 'Business Plan Preview',
    telechargementBusinessPlanPreview: 'Business Plan Downloaded',
    clickedBoutonDemandePourEnvoyerDossierCA: 'Demand CA Sent',
    upsellSonOffreEnPayant: 'Upsell Paid BP',
    clickedBoutonSuivantDansFunnelOnboarding: 'Funnel Onboarding',
    clickedBoutonRenvoyerEmailConfirmation: 'Resend Confirmation Email',
    statutCompteUpdatedEnValideDansBackendApp: 'Account Confirmed',
    pourcentageCompletionBPUpdatedDansBackendApp:
        'BP - Pourcentage Completion Update',
    scoringLeadUpdatedDansBackendApp: 'Scoring Lead Update',
    champPageGardeUpdated: 'BP - Page de Garde Update',
    champPageProjetUpdated: 'BP - Projet Update',
    champPageSocieteUpdated: 'BP - Société Update',
    champPagePrevisionnelUpdated: 'BP - Prévisionnel Update',
    optInCommunicationOnboarding: 'Opt-in Marketing',
    pagePrevisionnelComplete100pcent: 'BP - Prévisionnel Completed',
    pageProjetComplete100pcent: 'BP - Projet Completed',
    pageSocieteComplete100pcent: 'BP - Société Completed',
    pageEtudeMarcheComplete100pcent: 'BP - Marché Completed',
    pageGardeComplete100pcent: 'BP - Page de Garde Completed',
};
