export const enum EventName {
    'inscription' = 'inscription',
    'connexionApp' = 'connexionApp',
    'motDePasseOublie' = 'motDePasseOublie',
    'coachingPlanifie' = 'coachingPlanifie',
    'telechargeBusinessPlan' = 'telechargeBusinessPlan',
    'telechargementBusinessPlanPreview' = 'telechargementBusinessPlanPreview',
    'cliqueSurBoutonDemandePourEnvoyerDossierCA' = 'cliqueSurBoutonDemandePourEnvoyerDossierCA',
    'upsellSonOffreEnPayant' = 'upsellSonOffreEnPayant',
    'clickedBoutonSuivantDansFunnelOnboarding' = 'clickedBoutonSuivantDansFunnelOnboarding',
    'clickedBoutonRenvoyerEmailConfirmation' = 'clickedBoutonRenvoyerEmailConfirmation',
    'scoreUtilisateurChange' = 'scoreUtilisateurChange',
    'statutCompteUpdatedEnValideDansBackendApp' = 'statutCompteUpdatedEnValideDansBackendApp',
    'champPageGardeUpdated' = 'champPageGardeUpdated',
    'champPageProjetUpdated' = 'champPageProjetUpdated',
    'champPageSocieteUpdated' = 'champPageSocieteUpdated',
    'champPageEtudeMarcheUpdated' = 'champPageEtudeMarcheUpdated',
    'champPagePrevisionnelUpdated' = 'champPagePrevisionnelUpdated',
    'optInCommuniationOnboarding' = 'optInCommuniationOnboarding',
    'pagePrevisionnelComplete100pcent' = 'pagePrevisionnelComplete100pcent',
    'pageProjetComplete100pcent' = 'pageProjetComplete100pcent',
    'pageSocieteComplete100pcent' = 'pageSocieteComplete100pcent',
    'pageEtudeMarcheComplete100pcent' = 'pageEtudeMarcheComplete100pcent',
    'pageGardeComplete100pcent' = 'pageGardeComplete100pcent',
}
