export const intercomCommonFields = {
    nom: 'lastName',
    prenom: 'firstName',
    email: 'email',
    dateNaissance: 'birthday',
    adresse: 'address',
    telephone: 'phone',
    fonction: 'role',
    siteWeb: 'website',    
};

export const intercomMapCustomFields = {
    statutLeadEnvoyeAuCA: 'Statut lead envoyé au CA',
    raisonRejetStatutLead: 'Raison rejet statut lead',
    statutLeadsTelechargementBP: 'Statut lead téléchargement BP',
    statutCoaching: 'Statut coaching',
    formuleChoisie: 'Formule choisie',
    dateDerniereConnexionOuUpdate: 'Date derniere connexion ou update',
    compteValide: 'Compte valide',
    dateCreationCompte: 'Date création du compte',
    tailleEntreprise: 'Company size',
    statutJuridique: 'Statut juridique',
    tauxCompletionBP: 'Taux complétion BP',
    codeNAF: 'Code NAF',
    secteurActivite: 'Company industry',
    scoringJSE: 'Scoring JSE',
    titreNomProjet: 'Titre nom du projet',
    codePostal: 'Code postal',
    dateLancementActivite: 'Date lancement activité',
    chiffreAffairesAnnee1: 'Chiffre affaires année 1',
    dateDernierCoachingRealise: 'Date dernier coaching realise',
    demandeEnvoiProjetCA: 'Demande envoi projet au CA',
    accepteEmailMarketing: 'Accepte email marketing',
    BPGlobal: 'BP global',
    previsionnel: 'Prévisionnel',
    etudeMarche: 'Etude de marché',
    societe: 'Société',
    projet: 'Projet',
    pageGarde: 'Page de garde',
};
