export const intercomCommonFields = {
    nom: 'lastName',
    prenom: 'firstName',
    email: 'email',
    dateNaissance: 'birthday',
    adresse: 'address',
    telephone: 'phone',
    fonction: 'role',
    siteWeb: 'website',
    sexe: 'gender',
};

export const intercomMapCustomFields = {
    compteValide: 'Compte valide',
    nomProjet: 'Nom du projet',
    compteSupprime: 'Compte supprimé',
    'JSE App User Id': 'JSE App User Id',
    dateNaissance: 'Date de naissance',
    boutonEmailConfirmation: 'Renvoi email confirmation cliqué',
    dateDernierPDFTelecharge: 'Date dernier BP téléchargé',
    urlMotDePasseOublie: 'Lien mot de passe oublié',
    urlValidationCompte: 'Lien de validation du compte',
    dateValidationCompte: 'Date validation du compte',
    statutLeadEnvoyeAuCA: 'Statut lead envoyé au CA',
    raisonRejetStatutLead: 'Raison rejet statut lead',
    statutLeadsTelechargementBP: 'Téléchargement BP',
    statutCoaching: 'Statut coaching',
    coachingGratuitOffert: 'Coaching gratuit offert',
    formuleChoisie: 'Formule choisie',
    boutonFunnelOnboarding: 'Bouton suivant funnel onboard',
    dateDerniereConnexionOuUpdate: 'Date derniere connexion ou update',
    tailleEntreprise: 'Taille entreprise',
    statutJuridique: 'Statut juridique',
    tauxCompletionBP: 'Taux complétion BP',
    codeNAF: 'Code NAF',
    secteurActivite: 'Secteur activite',
    scoringJSE: 'Scoring JSE',
    titreNomProjet: 'Titre nom du projet',
    codePostal: 'Code postal',
    dateLancementActivite: 'Date lancement activité',
    chiffreAffairesAnnee1: 'Chiffre affaires année 1',
    dateDernierCoachingRealise: 'Date dernier coaching réalisé',
    dateProchainCoaching: 'Date prochain coaching',
    demandeEnvoiProjetCA: 'Demande envoi projet au CA',
    accepteEmailMarketing: 'Accepte email marketing',
    BPGlobal: 'BP global',
    previsionnel: 'Prévisionnel',
    etudeMarche: 'Etude de marché',
    societe: 'Société',
    projet: 'Projet',
    pageGarde: 'Page de garde',
    codePromoUtilise: 'Code promo utilisé',
    jseUserId: 'User id',
    lienVersPageConnexion: 'Lien page de connexion',
    lienVersPageBP: 'Lien interface bp',
};
